### ISSUE TITLE
Email body color not right in dark theme

### ISSUE THREAD

**Issue by Brendovisk** [drakkar1969/mailspring-libadwaita-theme#1]
Before:
![image](https://user-images.githubusercontent.com/71789884/204134814-dc4f2e20-a975-48a8-bb39-0fc6079c91ff.png)

After:
![image](https://user-images.githubusercontent.com/71789884/204134764-444d0faf-1435-47a9-8c7e-ddd001445754.png)

You can fix that by just adding the following selector: 

```css
.ignore-in-parent-frame {
    html, body {
        color: @text_color !important;
    }
}
```
